// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hudxvtbnzwvaqbcjbjzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1ZHh2dGJuend2YXFiY2pianpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTY3NzgsImV4cCI6MjA3NjE5Mjc3OH0.9qHq77shVb5xq_5NkoAcZ69tVcBptP1NUi7WyJTXUXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});